# Generated by Django 5.2.15 on 2026-07-04 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='banner',
        ),
    ]
