# Generated by Django 5.2.15 on 2026-07-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='id_card_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
